# Generated by Django 3.2.3 on 2023-12-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='album',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
