# Generated by Django 3.2.3 on 2023-12-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20231221_0048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
    ]
